version: '3'

services:
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    image: nodejs
    container_name: websocket
    restart: unless-stopped
    networks:
      - app-network
  
  webserver:
    image: nginx:mainline-alpine
    container_name: webserver
    restart: unless-stopped
    ports: 
      - "3030:3030"
    volumes:
      - web-root:/var/www/html
      - ./nginx-conf:/etc/nginx/conf.d
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
    depends_on:
      - nodejs
    networks:
      - app-network

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - web-root:/var/www/html
    depends_on:
      - webserver
    command: certonly --webroot --webroot-path=/var/www/html --email mightykim91@naver.com --agree-tos --no-eff-email --staging -d j3a405.p.ssafy.io
    # command: certonly --webroot --webroot-path=/var/www/html --email mightykim91@naver.com --agree-tos --no-eff-email --staging -d localhost

volumes:
  certbot-etc:
  certbot-var:
  web-root:
    driver: local
    driver_opts:
      type: none
      device: /home/ubuntu/socket_deploy/socket-server/views/
      # device: /Users/yeonsukim/Documents/socket-server/views
      o: bind
networks:
  app-network:
    driver: bridge